### ISSUE TITLE
Deprecate this formula

### ISSUE THREAD

**Issue by tbg** [cockroachdb/homebrew-go#5]
Our build system has changed to the point that there isn't a good reason to run a Go fork. Suggest deprecating (or flatout removing?) this formula.

**Comment by tbg** [comment]
cc @benesch

**Comment by benesch** [comment]
I think the parallel builds patch still shaves a reasonable amount off time off the compilation of `pkg/storage/engine`? Not sure; I think @tamird might have investigated at some point.

**Comment by tamird** [comment]
I've never used these patches on macOS, and if I ever investigated the time
savings on Linux, I didn't record them.

**Comment by benesch** [comment]
Ah, well, then you conjectured. In any case, I think I've fully obsoleted it if this lands: https://github.com/cockroachdb/cockroach/pull/17035.
